import Task from '@/components/task';

export const metadata = {
    title: 'Admin',
    description: 'Generated by create next app',
}
  
export default async function Admin() {
    return (
        <div>
            {/* Navbar */}
            <Task  />
            {/* give list of memebers */}
        </div>
    );
}
