// import { auth } from '@clerk/nextjs/server' 
import Navbar from '@/components/admin/Navbar';
import Task from '@/components/task';
import { currentUser } from '@clerk/nextjs/server';
// import { Organization } from '@clerk/nextjs/server';

export const metadata = {
    title: 'Admin',
    description: 'Generated by create next app',
}
  
// export async function getServerSideProps() {
//     // Fetch data from external API
//     const res = await fetch('https://api.github.com/repos/vercel/next.js')
//     const repo = await res.json()
//     // Pass data to the page via props
//     return { props: { repo } }
//   }

export default async function Admin() {
    // const { orgId } = auth();
    // console.log("Org ID : ",orgId)
    const user = await currentUser();
    // console.log(user ?? " ")
    // const data = Organization();

    return (
        <div>
            {/* Navbar */}
            <Navbar user={user.publicMetadata.username || " "} />
            {/* Tasks */}
            <Task  />
        </div>
    );
}
