import '../globals.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default function Layout({ children }) {
    const year = new Date().getFullYear();

    return (
        <section>
            {children}
        </section>
    )
}
